/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab8_franciscosantos;

import java.util.ArrayList;

/**
 *
 * @author Francisco Santos
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_agregar = new javax.swing.JDialog();
        Hadas = new javax.swing.JTabbedPane();
        Lamias = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tf_nombreLam = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        sp_estaturaLam = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        sp_edadLam = new javax.swing.JSpinner();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sp_alasLam = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        tf_saludLam = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tf_poderLam = new javax.swing.JTextField();
        bt_guardarLamias = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        sp_aletas = new javax.swing.JSpinner();
        jLabel39 = new javax.swing.JLabel();
        sp_branquias = new javax.swing.JSpinner();
        jLabel40 = new javax.swing.JLabel();
        Hamadriades = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        tf_nombreHam = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        sp_estaturaHam = new javax.swing.JSpinner();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        sp_edadHam = new javax.swing.JSpinner();
        jLabel22 = new javax.swing.JLabel();
        tf_arbol = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        sp_alasHam = new javax.swing.JSpinner();
        jLabel24 = new javax.swing.JLabel();
        tf_saludHam = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tf_poderHam = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        bt_guardarHamadriades = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        Silfide = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        tf_nombreSil = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        sp_estaturaSil = new javax.swing.JSpinner();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        sp_edadSil = new javax.swing.JSpinner();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        sp_alasSil = new javax.swing.JSpinner();
        jLabel32 = new javax.swing.JLabel();
        tf_saludSil = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        tf_poderSil = new javax.swing.JTextField();
        bt_guardarSilfide = new javax.swing.JButton();
        jLabel35 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        Salamandras = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreSal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sp_estatura = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sp_alasSal = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_saludSal = new javax.swing.JTextField();
        tf_poderSal = new javax.swing.JTextField();
        bt_guardarSalamandra = new javax.swing.JButton();
        sp_edadSal = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jd_modificar = new javax.swing.JDialog();
        jd_eliminar = new javax.swing.JDialog();
        jd_pelea = new javax.swing.JDialog();
        jLabel45 = new javax.swing.JLabel();
        jl_pelea = new javax.swing.JLabel();
        jl_eliminar = new javax.swing.JLabel();
        jl_modidficar = new javax.swing.JLabel();
        jl_agregar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        abrir = new javax.swing.JMenuItem();
        guardar = new javax.swing.JMenuItem();
        guardarComo = new javax.swing.JMenuItem();
        Salir = new javax.swing.JMenuItem();
        About = new javax.swing.JMenuItem();

        jd_agregar.setTitle("Agregar");

        Lamias.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Nombre");
        Lamias.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 52, -1, -1));
        Lamias.add(tf_nombreLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 52, 146, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Estatura");
        Lamias.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 93, -1, -1));

        sp_estaturaLam.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        sp_estaturaLam.setMaximumSize(new java.awt.Dimension(15, 15));
        sp_estaturaLam.setMinimumSize(new java.awt.Dimension(1, 1));
        Lamias.add(sp_estaturaLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 90, 49, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("cm");
        Lamias.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 93, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setText("Edad");
        Lamias.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 131, -1, -1));

        sp_edadLam.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Lamias.add(sp_edadLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 128, 50, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("años");
        Lamias.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 131, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Alas");
        Lamias.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 213, -1, -1));

        sp_alasLam.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));
        Lamias.add(sp_alasLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 210, 50, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Salud");
        Lamias.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 251, -1, -1));

        tf_saludLam.setText("683");
        tf_saludLam.setEnabled(false);
        Lamias.add(tf_saludLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 248, 36, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Poder");
        Lamias.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 301, -1, -1));

        tf_poderLam.setText("71");
        tf_poderLam.setEnabled(false);
        Lamias.add(tf_poderLam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 298, 36, -1));

        bt_guardarLamias.setText("Guardar");
        bt_guardarLamias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarLamiasMouseClicked(evt);
            }
        });
        Lamias.add(bt_guardarLamias, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 286, 84, 44));

        jLabel37.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel37.setText("Lamias");
        Lamias.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 11, 165, 35));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setText("Aleta");
        Lamias.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 172, -1, -1));

        sp_aletas.setModel(new javax.swing.SpinnerNumberModel(5, 5, null, 1));
        Lamias.add(sp_aletas, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 169, 51, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setText("Branquias");
        Lamias.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 172, -1, -1));

        sp_branquias.setModel(new javax.swing.SpinnerNumberModel(1, 1, 7, 1));
        Lamias.add(sp_branquias, new org.netbeans.lib.awtextra.AbsoluteConstraints(258, 169, 44, -1));

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab8_franciscosantos/lamia.jpg"))); // NOI18N
        jLabel40.setText("jLabel40");
        Lamias.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));

        Hadas.addTab("Lamias", Lamias);

        Hamadriades.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setText("Nombre");
        Hamadriades.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        Hamadriades.add(tf_nombreHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 57, 146, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Estatura");
        Hamadriades.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 108, -1, -1));

        sp_estaturaHam.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        sp_estaturaHam.setMaximumSize(new java.awt.Dimension(15, 15));
        sp_estaturaHam.setMinimumSize(new java.awt.Dimension(1, 1));
        Hamadriades.add(sp_estaturaHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 105, 49, -1));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("cm");
        Hamadriades.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 108, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Edad");
        Hamadriades.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 153, -1, -1));

        sp_edadHam.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Hamadriades.add(sp_edadHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 150, 50, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("años");
        Hamadriades.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 153, -1, -1));

        tf_arbol.setText("173");
        tf_arbol.setEnabled(false);
        Hamadriades.add(tf_arbol, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 40, 20));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Alas");
        Hamadriades.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, -1, -1));

        sp_alasHam.setModel(new javax.swing.SpinnerNumberModel(2, 2, null, 1));
        Hamadriades.add(sp_alasHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 191, 50, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Salud");
        Hamadriades.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 238, -1, -1));

        tf_saludHam.setText("683");
        tf_saludHam.setEnabled(false);
        Hamadriades.add(tf_saludHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 235, 36, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Poder");
        Hamadriades.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 288, -1, -1));

        tf_poderHam.setText("71");
        tf_poderHam.setEnabled(false);
        Hamadriades.add(tf_poderHam, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 285, 36, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel44.setText("Arbol");
        Hamadriades.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 234, 40, 20));

        bt_guardarHamadriades.setText("Guardar");
        bt_guardarHamadriades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarHamadriadesMouseClicked(evt);
            }
        });
        Hamadriades.add(bt_guardarHamadriades, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 273, 84, 44));

        jLabel36.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Hamadriades");
        Hamadriades.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 11, 165, 35));

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab8_franciscosantos/driade.jpg"))); // NOI18N
        jLabel41.setText("jLabel41");
        Hamadriades.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));

        Hadas.addTab("Hamadriades", Hamadriades);

        Silfide.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nombre");
        Silfide.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        Silfide.add(tf_nombreSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 57, 146, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Estatura");
        Silfide.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 108, -1, -1));

        sp_estaturaSil.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        sp_estaturaSil.setMaximumSize(new java.awt.Dimension(15, 15));
        sp_estaturaSil.setMinimumSize(new java.awt.Dimension(1, 1));
        Silfide.add(sp_estaturaSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 105, 49, -1));

        jLabel28.setText("cm");
        Silfide.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 108, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Edad");
        Silfide.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 153, -1, -1));

        sp_edadSil.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Silfide.add(sp_edadSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 150, 50, -1));

        jLabel30.setText("años");
        Silfide.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 153, -1, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Alas");
        Silfide.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, -1, -1));

        sp_alasSil.setModel(new javax.swing.SpinnerNumberModel(6, 6, null, 1));
        Silfide.add(sp_alasSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 191, 50, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Salud");
        Silfide.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 238, -1, -1));

        tf_saludSil.setText("683");
        tf_saludSil.setEnabled(false);
        Silfide.add(tf_saludSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 235, 36, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Poder");
        Silfide.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 288, -1, -1));

        tf_poderSil.setText("71");
        tf_poderSil.setEnabled(false);
        Silfide.add(tf_poderSil, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 285, 36, -1));

        bt_guardarSilfide.setText("Guardar");
        bt_guardarSilfide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarSilfideMouseClicked(evt);
            }
        });
        Silfide.add(bt_guardarSilfide, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 273, 84, 44));

        jLabel35.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Silfide");
        Silfide.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 11, 165, 35));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab8_franciscosantos/silfides.png"))); // NOI18N
        jLabel42.setText("jLabel42");
        Silfide.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));

        Hadas.addTab("Silfide", Silfide);

        Salamandras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre");
        Salamandras.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        Salamandras.add(tf_nombreSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 57, 146, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Estatura");
        Salamandras.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 108, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Edad");
        Salamandras.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 153, 40, -1));

        sp_estatura.setModel(new javax.swing.SpinnerNumberModel(1, 1, 15, 1));
        sp_estatura.setMaximumSize(new java.awt.Dimension(15, 15));
        sp_estatura.setMinimumSize(new java.awt.Dimension(1, 1));
        Salamandras.add(sp_estatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 105, 49, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("cm");
        Salamandras.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 108, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Alas");
        Salamandras.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 197, 40, -1));

        sp_alasSal.setModel(new javax.swing.SpinnerNumberModel(16, 16, null, 1));
        Salamandras.add(sp_alasSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 191, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Salud");
        Salamandras.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 238, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Poder");
        Salamandras.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 288, -1, -1));

        tf_saludSal.setText("683");
        tf_saludSal.setEnabled(false);
        Salamandras.add(tf_saludSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 235, 36, -1));

        tf_poderSal.setText("71");
        tf_poderSal.setEnabled(false);
        Salamandras.add(tf_poderSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 285, 36, -1));

        bt_guardarSalamandra.setText("Guardar");
        bt_guardarSalamandra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_guardarSalamandraMouseClicked(evt);
            }
        });
        Salamandras.add(bt_guardarSalamandra, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 273, 84, 44));

        sp_edadSal.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        Salamandras.add(sp_edadSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 150, 50, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("años");
        Salamandras.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(177, 153, -1, -1));

        jLabel34.setFont(new java.awt.Font("Sylfaen", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Salamandras");
        Salamandras.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(86, 11, 165, 35));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab8_franciscosantos/salamandra.jpg"))); // NOI18N
        jLabel43.setText("jLabel43");
        Salamandras.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));

        Hadas.addTab("Salamandras", Salamandras);

        javax.swing.GroupLayout jd_agregarLayout = new javax.swing.GroupLayout(jd_agregar.getContentPane());
        jd_agregar.getContentPane().setLayout(jd_agregarLayout);
        jd_agregarLayout.setHorizontalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hadas)
        );
        jd_agregarLayout.setVerticalGroup(
            jd_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Hadas, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jd_modificar.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jd_eliminarLayout = new javax.swing.GroupLayout(jd_eliminar.getContentPane());
        jd_eliminar.getContentPane().setLayout(jd_eliminarLayout);
        jd_eliminarLayout.setHorizontalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_eliminarLayout.setVerticalGroup(
            jd_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jd_peleaLayout = new javax.swing.GroupLayout(jd_pelea.getContentPane());
        jd_pelea.getContentPane().setLayout(jd_peleaLayout);
        jd_peleaLayout.setHorizontalGroup(
            jd_peleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jd_peleaLayout.setVerticalGroup(
            jd_peleaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jLabel45.setText("jLabel45");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_pelea.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jl_pelea.setForeground(new java.awt.Color(255, 255, 255));
        jl_pelea.setText("Pelea");
        jl_pelea.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_peleaMouseClicked(evt);
            }
        });
        getContentPane().add(jl_pelea, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 200, 50));

        jl_eliminar.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jl_eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jl_eliminar.setText("Eliminar");
        jl_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_eliminarMouseClicked(evt);
            }
        });
        getContentPane().add(jl_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 160, 50));

        jl_modidficar.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jl_modidficar.setForeground(new java.awt.Color(255, 255, 255));
        jl_modidficar.setText("Modificar");
        jl_modidficar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_modidficarMouseClicked(evt);
            }
        });
        getContentPane().add(jl_modidficar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 40));

        jl_agregar.setFont(new java.awt.Font("Ravie", 0, 24)); // NOI18N
        jl_agregar.setForeground(new java.awt.Color(255, 255, 255));
        jl_agregar.setText("Agregar");
        jl_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jl_agregarMouseClicked(evt);
            }
        });
        getContentPane().add(jl_agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 150, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lab8_franciscosantos/Fairy.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 360));

        jMenu3.setText("Opciones");

        abrir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        abrir.setText("Abrir");
        abrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirActionPerformed(evt);
            }
        });
        jMenu3.add(abrir);

        guardar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        guardar.setText("Guardar");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jMenu3.add(guardar);

        guardarComo.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        guardarComo.setText("Guardar Como");
        jMenu3.add(guardarComo);

        Salir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        Salir.setText("Salir");
        jMenu3.add(Salir);

        About.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        About.setText("About");
        jMenu3.add(About);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        
    }//GEN-LAST:event_guardarActionPerformed

    private void jl_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_agregarMouseClicked
        jd_agregar.pack();
        jd_agregar.setModal(true);
        jd_agregar.setVisible(true);
        jd_agregar.setLocationRelativeTo(this);
    }//GEN-LAST:event_jl_agregarMouseClicked

    private void bt_guardarLamiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarLamiasMouseClicked
        lam.add(new Lamias((Integer)sp_aletas.getValue(),(Integer)sp_branquias.getValue(),tf_nombreLam.getText(),(Integer)sp_edadLam.getValue(),Double.parseDouble(tf_saludLam.getText()),(Integer)sp_estaturaLam.getValue(),Integer.parseInt(tf_poderLam.getText())));
        
        
    }//GEN-LAST:event_bt_guardarLamiasMouseClicked

    private void bt_guardarHamadriadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarHamadriadesMouseClicked
       lam.add(new Hamadriades(Integer.parseInt(tf_arbol.getText()), tf_nombreHam.getText(), (Integer)sp_edadHam.getValue(), Double.parseDouble(tf_saludHam.getText()), (Integer)sp_estaturaHam.getValue(), Integer.parseInt(tf_poderHam.getText())));
    }//GEN-LAST:event_bt_guardarHamadriadesMouseClicked

    private void bt_guardarSilfideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarSilfideMouseClicked
    lam.add(new Silfides((Integer)sp_alasSil.getValue(), tf_nombreSil.getText(), (Integer)sp_edadSil.getValue(), Double.parseDouble(tf_saludSil.getText()), (Integer)sp_estaturaSil.getValue(), Integer.parseInt(tf_poderSil.getText())));
    }//GEN-LAST:event_bt_guardarSilfideMouseClicked

    private void bt_guardarSalamandraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_guardarSalamandraMouseClicked
        Hadas s = new Salamandra((Integer)sp_alasSal.getValue(), tf_nombreSal.getText(), (Integer)sp_edadSal.getValue(), Double.parseDouble(tf_saludSal.getText()), (Integer)sp_estatura.getValue(), Integer.parseInt(tf_poderSal.getText()));
        lam.add(s);
    }//GEN-LAST:event_bt_guardarSalamandraMouseClicked

    private void jl_modidficarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_modidficarMouseClicked
        jd_modificar.pack();
        jd_modificar.setModal(true);
        jd_modificar.setVisible(true);
        jd_modificar.setLocationRelativeTo(this);
    }//GEN-LAST:event_jl_modidficarMouseClicked

    private void jl_eliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_eliminarMouseClicked
        jd_eliminar.pack();
        jd_eliminar.setModal(true);
        jd_eliminar.setVisible(true);
        jd_eliminar.setLocationRelativeTo(this);
    }//GEN-LAST:event_jl_eliminarMouseClicked

    private void jl_peleaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jl_peleaMouseClicked
        jd_pelea.pack();
        jd_pelea.setModal(true);
        jd_pelea.setVisible(true);
        jd_pelea.setLocationRelativeTo(this);
    }//GEN-LAST:event_jl_peleaMouseClicked

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        
    }//GEN-LAST:event_abrirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem About;
    private javax.swing.JTabbedPane Hadas;
    private javax.swing.JPanel Hamadriades;
    private javax.swing.JPanel Lamias;
    private javax.swing.JPanel Salamandras;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JPanel Silfide;
    private javax.swing.JMenuItem abrir;
    private javax.swing.JButton bt_guardarHamadriades;
    private javax.swing.JButton bt_guardarLamias;
    private javax.swing.JButton bt_guardarSalamandra;
    private javax.swing.JButton bt_guardarSilfide;
    private javax.swing.JMenuItem guardar;
    private javax.swing.JMenuItem guardarComo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JDialog jd_agregar;
    private javax.swing.JDialog jd_eliminar;
    private javax.swing.JDialog jd_modificar;
    private javax.swing.JDialog jd_pelea;
    private javax.swing.JLabel jl_agregar;
    private javax.swing.JLabel jl_eliminar;
    private javax.swing.JLabel jl_modidficar;
    private javax.swing.JLabel jl_pelea;
    private javax.swing.JSpinner sp_alasHam;
    private javax.swing.JSpinner sp_alasLam;
    private javax.swing.JSpinner sp_alasSal;
    private javax.swing.JSpinner sp_alasSil;
    private javax.swing.JSpinner sp_aletas;
    private javax.swing.JSpinner sp_branquias;
    private javax.swing.JSpinner sp_edadHam;
    private javax.swing.JSpinner sp_edadLam;
    private javax.swing.JSpinner sp_edadSal;
    private javax.swing.JSpinner sp_edadSil;
    private javax.swing.JSpinner sp_estatura;
    private javax.swing.JSpinner sp_estaturaHam;
    private javax.swing.JSpinner sp_estaturaLam;
    private javax.swing.JSpinner sp_estaturaSil;
    private javax.swing.JTextField tf_arbol;
    private javax.swing.JTextField tf_nombreHam;
    private javax.swing.JTextField tf_nombreLam;
    private javax.swing.JTextField tf_nombreSal;
    private javax.swing.JTextField tf_nombreSil;
    private javax.swing.JTextField tf_poderHam;
    private javax.swing.JTextField tf_poderLam;
    private javax.swing.JTextField tf_poderSal;
    private javax.swing.JTextField tf_poderSil;
    private javax.swing.JTextField tf_saludHam;
    private javax.swing.JTextField tf_saludLam;
    private javax.swing.JTextField tf_saludSal;
    private javax.swing.JTextField tf_saludSil;
    // End of variables declaration//GEN-END:variables
ArrayList<Hadas> lam= new ArrayList();
String path = "./hadas.bin";
AdminBinarios ab = new AdminBinarios(path);

}
